export const provinciasCuba = [
  {
    nombre: 'Pinar del Río',
    municipios: [
      'Pinar del Río',
      'Consolación del Sur',
      'Guane',
      'La Palma',
      'Los Palacios',
      'Mantua',
      'Minas de Matahambre',
      'San Juan y Martínez',
      'San Luis',
      'Sandino',
      'Viñales',
    ],
  },
  {
    nombre: 'Artemisa',
    municipios: [
      'Alquízar',
      'Artemisa',
      'Bauta',
      'Caimito',
      'Candelaria',
      'Guanajay',
      'Güira de Melena',
      'Mariel',
      'San Antonio de los Baños',
      'San Cristóbal',
    ],
  },
  {
    nombre: 'La Habana',
    municipios: [
      'Arroyo Naranjo',
      'Boyeros',
      'Centro Habana',
      'Cerro',
      'Cotorro',
      'Diez de Octubre',
      'Guanabacoa',
      'Habana del Este',
      'Habana Vieja',
      'La Lisa',
      'Marianao',
      'Playa',
      'Plaza de la Revolución',
      'Regla',
      'San Miguel del Padrón',
    ],
  },
  {
    nombre: 'Mayabeque',
    municipios: [
      'Batabanó',
      'Bejucal',
      'Güines',
      'Jaruco',
      'Madruga',
      'Melena del Sur',
      'Nueva Paz',
      'Quivicán',
      'San José de las Lajas',
      'San Nicolás',
    ],
  },
  {
    nombre: 'Matanzas',
    municipios: [
      'Cardenas',
      'Colón',
      'Jovellanos',
      'Limonar',
      'Los Arabos',
      'Martí',
      'Matanzas',
      'Pedro Betancourt',
      'Perico',
      'Unión de Reyes',
    ],
  },
  {
    nombre: 'Villa Clara',
    municipios: [
      'Camajuaní',
      'Caibarién',
      'Cifuentes',
      'Corralillo',
      'Encrucijada',
      'Manicaragua',
      'Placetas',
      'Quemado de Güines',
      'Ranchuelo',
      'Remedios',
      'Sagua la Grande',
      'Santa Clara',
      'Santo Domingo',
    ],
  },
  {
    nombre: 'Cienfuegos',
    municipios: [
      'Aguada de Pasajeros',
      'Cienfuegos',
      'Cumanayagua',
      'Lajas',
      'Palmira',
      'Rodas',
      'Cruces',
      'Abreus',
    ],
  },
  {
    nombre: 'Sancti Spíritus',
    municipios: [
      'Cabaiguán',
      'Fomento',
      'Jatibonico',
      'La Sierpe',
      'Sancti Spíritus',
      'Taguasco',
      'Trinidad',
      'Yaguajay',
    ],
  },
  {
    nombre: 'Ciego de Ávila',
    municipios: [
      'Baraguá',
      'Bolivia',
      'Chambas',
      'Ciego de Ávila',
      'Ciro Redondo',
      'Florencia',
      'Majagua',
      'Morón',
      'Primero de Enero',
      'Venezuela',
    ],
  },
  {
    nombre: 'Camagüey',
    municipios: [
      'Camagüey',
      'Carlos Manuel de Céspedes',
      'Esmeralda',
      'Florida',
      'Guaimaro',
      'Jimaguayú',
      'Minas',
      'Najasa',
      'Nuevitas',
      'Santa Cruz del Sur',
      'Sibanicú',
      'Sierra de Cubitas',
      'Vertientes',
    ],
  },
  {
    nombre: 'Las Tunas',
    municipios: [
      'Amancio',
      'Colombia',
      'Jesús Menéndez',
      'Jobabo',
      'Las Tunas',
      'Majibacoa',
      'Manatí',
      'Puerto Padre',
    ],
  },
  {
    nombre: 'Holguín',
    municipios: [
      'Antilla',
      'Báguanos',
      'Banes',
      'Cacocum',
      'Calixto García',
      'Cueto',
      'Frank País',
      'Gibara',
      'Holguín',
      'Mayarí',
      'Moa',
      'Rafael Freyre',
      'Sagua de Tánamo',
      'Urbano Noris',
    ],
  },
  {
    nombre: 'Granma',
    municipios: [
      'Bartolomé Masó',
      'Bayamo',
      'Buey Arriba',
      'Campechuela',
      'Cauto Cristo',
      'Guisa',
      'Jiguaní',
      'Manzanillo',
      'Media Luna',
      'Niquero',
      'Pilón',
      'Río Cauto',
      'Yara',
    ],
  },
  {
    nombre: 'Santiago de Cuba',
    municipios: [
      'Contramaestre',
      'Guamá',
      'Mella',
      'Palma Soriano',
      'San Luis',
      'Santiago de Cuba',
      'Segundo Frente',
      'Songo-La Maya',
      'Tercer Frente',
    ],
  },
  {
    nombre: 'Guantánamo',
    municipios: [
      'Baracoa',
      'Caimanera',
      'El Salvador',
      'Guantánamo',
      'Imías',
      'Maisí',
      'Manuel Tames',
      'Niceto Pérez',
      'San Antonio del Sur',
      'Yateras',
    ],
  },
  {
    nombre: 'Isla de la Juventud',
    municipios: ['Isla de la Juventud'],
  },
]
